<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Voluta.Checkpoints.File.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voluta\Voluta.csproj" />
    <ProjectReference Include="..\..\src\Voluta.Checkpoints.File\Voluta.Checkpoints.File.csproj" />
    <ProjectReference Include="..\..\src\Voluta.Testing\Voluta.Testing.csproj" />
  </ItemGroup>

</Project>
