<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Voluta.Checkpoints.Postgres.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
    <PackageReference Include="Npgsql" Version="9.0.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.3.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voluta.Checkpoints.Postgres\Voluta.Checkpoints.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Voluta.DependencyInjection\Voluta.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Voluta.Testing\Voluta.Testing.csproj" />
  </ItemGroup>

</Project>
