<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Voluta.Checkpoints.EntityFrameworkCore.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voluta.Checkpoints.EntityFrameworkCore\Voluta.Checkpoints.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Voluta.DependencyInjection\Voluta.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Voluta.Testing\Voluta.Testing.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.*" />
  </ItemGroup>

</Project>
