<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>StemmaGraph.Checkpoints.File.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StemmaGraph.Checkpoints.File\StemmaGraph.Checkpoints.File.csproj" />
    <ProjectReference Include="..\..\src\StemmaGraph.Testing\StemmaGraph.Testing.csproj" />
  </ItemGroup>

</Project>
