<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>
      AWS S3 (and S3-compatible) C-shape checkpointer for Voluta.
    </Description>
    <PackageTags>$(PackageTags);checkpoint;s3;aws;persistence</PackageTags>
    <RootNamespace>Voluta.Checkpoints.S3</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.*" />
    <ProjectReference Include="..\Voluta.Abstractions\Voluta.Abstractions.csproj" />
  </ItemGroup>

</Project>
