<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Voluta.Samples.HelloWorld</RootNamespace>
    <IsPackable>false</IsPackable>
    <Description>
      01-HelloWorld: simulated ReAct loop (agent ⇄ tools) streaming channel updates.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voluta\Voluta.csproj" />
  </ItemGroup>

</Project>
