<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\checkpoints\Voluta.Checkpoints.Redis\Voluta.Checkpoints.Redis.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
    <PackageReference Include="NSubstitute" Version="5.3.*" />
    <PackageReference Remove="Meziantou.Analyzer" />
    <PackageReference Remove="Microsoft.VisualStudio.Threading.Analyzers" />
  </ItemGroup>

</Project>
